// Writes assets/history.js from this repository's git log: the ticks under the Rewind slider.
// Runs at deploy (see .github/workflows/pages.yml); run it by hand after committing to keep the file fresh.
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");
const out = path.join(__dirname, "..", "assets", "history.js");
let lines = [];
try {
  lines = execSync("git log --reverse --date=short --format=%h%x1f%ad%x1f%s", { encoding: "utf8" }).trim().split("\n").filter(Boolean);
} catch (e) {
  console.error("gen-history: not a git checkout, keeping the old file");
  process.exit(0);
}
const commits = lines.map((l) => { const [h, date, msg] = l.split("\x1f"); return { h, date, msg }; });
const src = `// generated by scripts/gen-history.js — the commits of this site, oldest first\nwindow.HISTORY = ${JSON.stringify({ generated: new Date().toISOString().slice(0, 10), commits }, null, 0)};\n`;
fs.writeFileSync(out, src);
console.log(`gen-history: ${commits.length} commits → ${path.relative(process.cwd(), out)}`);
