// Builds assets/name-path.js: glyph outlines of the owner's name in the display face, as SVG path data.
const opentype = require('opentype.js');
const fs = require('fs');
const D = {}; new Function('window', fs.readFileSync('__dirname + '/../assets/projects.js', 'utf8'))(D);
const name = D.PORTFOLIO.name.toUpperCase();
const font = opentype.parse(fs.readFileSync(process.argv[2] || 'Bricolage-c.woff').buffer);
const em = font.unitsPerEm, asc = font.ascender, desc = font.descender;
const tracking = -0.045 * em; // matches the CSS letter-spacing on the hero
const lines = name.split(/\s+/).map((word) => {
  let x = 0; const glyphs = [];
  const gs = font.stringToGlyphs(word);
  gs.forEach((g, i) => {
    const p = g.getPath(x, asc, em); // baseline at y = ascender, y grows downward
    glyphs.push({ ch: word[i], d: p.toPathData(2), x, adv: g.advanceWidth });
    x += g.advanceWidth + tracking;
    if (i < gs.length - 1) x += font.getKerningValue(g, gs[i + 1]) || 0;
  });
  return { word, width: Math.round(x - tracking), glyphs };
});
const out = { em, asc, desc, height: asc - desc, lines };
fs.writeFileSync('__dirname + '/../assets/name-path.js', '// Generated by scripts/gen-name.js from the display face. Glyph outlines of the name, in font units.\nwindow.NAME_PATHS = ' + JSON.stringify(out) + ';\n');
console.log('em', em, 'asc', asc, 'desc', desc, lines.map(l => l.word + ':' + l.width + ' glyphs=' + l.glyphs.length + ' dlen=' + l.glyphs.reduce((a, g) => a + g.d.length, 0)));
